version: '3'

services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oms_api_development

  web:
    image: hureradevsinc/aws-project:latest
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app/volume
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/oms_api_development

volumes:
  db_data: